% Remove a plot from a specific model
% 
% Usage:
%   arRemovePlot( m, p, force )
%
%   m       - Model ID
%   ps      - Plot IDs (0 indicates last plot)
%   force   - Force deletion of plot. By default, the function will not
%             remove plots that are associated by a def file (i.e. not
%             generated by arSplitPlot)
%
% Hint: Determine plot IDs by arFindPlot

function arRemovePlot(m, ps, force)
    global ar;
    
    if ~exist( 'force', 'var' )
        force = 0;
    end
    
    if ( m > numel( ar.model ) )
        error( 'Model does not exist' );
    end
    
    jp = 1;
    while( jp <= numel(ps) )
        if ( ps(jp) < 1 )
            ps(jp) = numel( ar.model(m).plot ) - p(jp);
        end
        if ( ps(jp) > numel( ar.model(m).plot ) )
            error( 'Plot %d does not exist', p(jp) );
        end
        % Is this a core plot?
        if ( ~force && ( ~isfield( ar.model(m).plot(ps(jp)), 'origin' ) || isempty( ar.model(m).plot(ps(jp)).origin ) ) )
            warning( 'Not deleting plot %d since it is a core plot (directly specified by a def file). If you wish to delete it anyway, provide force = 1', ps(jp) );
            ps(jp) = [];
        else
            jp = jp + 1;
        end
    end
    
    ar.model(m).plot(ps) = [];
    ar.model(m).qPlotXs(ps) = [];
    ar.model(m).qPlotYs(ps) = [];
    ar.model(m).qPlotVs(ps) = [];
end