% Select which sensitivity analysis to perform
% 1 - Parameters without ruxolitinib treatment (finding an optimal intervention)
% 2 - Modifiable parameters after ruxolitinib treatment (how can we further optimize?)
% 3 - All parameters after intervention
% 4 - Parameters with ruxolitinib treatment (finding an optimal intervention)
parameterSelection = 4;

% Select which objective
% 1 - Integral of each APP gene
% 2 - Measurement time point
objectiveSelection = 1;

% Model and condition
m = 1;
cnd = arFindCondition('variable_prediction_TC');
start = find(ar.model(m).condition(cnd).tFine>=0,1);
final = find((ar.model(m).condition(cnd).tFine-1440)>0, 1);

% IL-6 dose
il6 = 100;

% Find IDs of APP genes
names = {'SOCS3RNA', 'CXCL10RNA', 'FGGRNA', 'HAMPRNA', 'IL33RNA', 'APCSRNA', 'HPRNA', 'HPXRNA' };
for a = 1 : length( names )
    ids(a) = find( ismember( ar.model.x, names{a} ) );
end

switch( objectiveSelection )
    case 1
        obj1 = @(t,y)trapz(t(start:final), y(start:final)); % Integral of APP genes
        obj  = @(id)obj1( ar.model(m).condition(cnd).tFine, ar.model(m).condition(cnd).xFineSimu(:, ids(id)) );
    case 2
        obj1 = @(t,y)y(final);                              % Single time point
        obj  = @(id)obj1( ar.model(m).condition(cnd).tFine, ar.model(m).condition(cnd).xFineSimu(:, ids(id)) );
end

parNames = [];
parIDs = [];
switch( parameterSelection )
    case 1
        pars = { ...
            'gp130_pro',        'Receptor production'; ...
            'gp130_deg',        'Receptor degradation'; ...
            'jak1_act_basal',   'Basal receptor activation'; ...
            'jak1_act_il6',     'Receptor activation by IL6'; ...
            'jak1_gp130_dea', 	'Dephosphorylation of receptor'; ...
            'stat3_act_gp130',  'Activation of STAT3'; ...
            'stat3_imp',        'Import of STAT3'; ...
            'stat3_exp',        'Export of STAT3'; ...
            'socs3rna_pro',     'SOCS3 mRNA production'; ...
            'socs3rna_delay',   'SOCS3 mRNA delay'; ...
            'socs3rna_des',     'SOCS3 mRNA degradation'; ...
            'socs3_pro',        'SOCS3 translation'; ...
            'socs3_des',        'SOCS3 degradation'; ...
            'socs3_assoc',      'SOCS3 mediated degradation'; ...
            'stat3_inh_socs3',  'SOCS3 receptor inhibition'; ...
            'total_STAT3',      'Total STAT3' ...
            };
        ruxdose = 0;
        parIDs = arFindPar( pars(:,1), 'exact', 'preserve' );       
        parNames = pars(:,2);
    case 2
        ruxdose = 500;
    case 3
        parIDs = setdiff(setdiff(setdiff(setdiff(setdiff(arFindPar('_', 'dynamic'), arFindPar('knot')), arFindPar('scale')),arFindPar('loc')),arFindPar('input_')),arFindPar('var'));
        ruxdose = 500;
    case 4
        pars = { ...
            'gp130_pro',        'Receptor production'; ...
            'gp130_deg',        'Receptor degradation'; ...
            'jak1_act_basal',   'Basal receptor activation'; ...
            'jak1_act_il6',     'Receptor activation by IL6'; ...
            'jak1_gp130_dea', 	'Dephosphorylation of receptor'; ...
            'stat3_act_gp130',  'Activation of STAT3'; ...
            'stat3_imp',        'Import of STAT3'; ...
            'stat3_exp',        'Export of STAT3'; ...
            'socs3rna_pro',     'SOCS3 mRNA production'; ...
            'socs3rna_delay',   'SOCS3 mRNA delay'; ...
            'socs3rna_des',     'SOCS3 mRNA degradation'; ...
            'socs3_pro',        'SOCS3 translation'; ...
            'socs3_des',        'SOCS3 degradation'; ...
            'socs3_assoc',      'SOCS3 mediated degradation'; ...
            'stat3_inh_socs3',  'SOCS3 receptor inhibition'; ...
            'total_STAT3',      'Total STAT3'; ...
            'rux_degrade',      'Ruxolitinib degradation'; ...
            };
        parIDs = arFindPar( pars(:,1), 'exact', 'preserve' );       
        parNames = pars(:,2);
        ruxdose = 500;
end

ar.qLog10( arFindPar({'input_rux1', 'input_rux2', 'input_rux3', 'var_il6'} ) ) = 0;
ar.p( arFindPar('input_rux1') ) = ruxdose;
ar.p( arFindPar('input_rux2') ) = 0;
ar.p( arFindPar('input_rux3') ) = 0;
ar.p( arFindPar('var_il6') ) = il6;

% Compatibility with 'modern' D2D
ar.ple=[];
ar.config.skipSim=0;